### ISSUE TITLE
Error on package install

### ISSUE THREAD

**Issue by MatteoGauthier** [code-tribe/nuxt-netlify-cms-starter#5]
```
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-svg-co
re/-/fontawesome-svg-core-1.2.19.tgz: Request failed \"401 Unauthorized\"".
```

**Comment by code-tribe** [comment]
Hi @MatteoGauthier sorry for the slow reply on this. I've just pushed an update which should fix and address this issue, but it stems from the `yarn.lock` file. Removing the lock file and reinstalling the dependencies should work, but otherwise, the update to this project should fix any further issues.
